#run locally
DB_USR: goo
DB_PASS: goo
DB_NAME: goo
DB_ADDR: localhost:5432
FIREBASE_CREDENTIALS: ../srv/starry-axis-411305-firebase-adminsdk-ttsc1-a6b79563d4.json
GCP_BUCKET_NAME: litter3-olo-gcp.appspot.com
ADDRESS: :8080
