runtime: go113
main: ./cmd
instance_class: F1
env_variables:
  DB_USR: postgres
  DB_PASS: budetojizda
  DB_NAME: postgres
  DB_ADDR: /cloudsql/litter3-olo-gcp:europe-west1:postgis/.s.PGSQL.5432
  FIREBASE_CREDENTIALS: ./srv/litter3-olo-gcp-firebase-adminsdk-6ar5p-9f1130c1cc.json
  GCP_BUCKET_NAME: litter3-olo-gcp.appspot.com
  ADDRESS: :80
  PROD: yes